drm: samsung: dsim: fix printf format
display/samsung/exynos_drm_dsim.c:2429:31: error: field width should have type 'int', but argument has type 'size_t' (aka 'unsigned long') [-Werror,-Wformat]
                logbuffer_log(dsim->log, "%*phN", sz, tx_buf);
                                          ~~^     ~~

Fixes: 293376435767 ("drm: samsung: use logbuffer to record dsi commands")
Test: TH
Bug: 348164658
Change-Id: I54af657692a4d952426e699b8337cc678171e640
Signed-off-by: André Draszik <draszik@google.com>